Add workflow start exit endpoints
equinor/inspection-data-analyzer pull request #38
Opened 2024-11-13 11:31 UTC by olaals

2024-11-14 06:08 UTC, Christdej requested changes

2024-11-14 06:08 UTC, Christdej commented on api/Controllers/WorkflowsControlller.cs
> +public class WorkflowsController(ILogger<InspectionDataController> logger, IInspectionDataService inspectionDataService) : ControllerBase
Can remove logger as it is unused, or we can use it

2024-11-14 06:08 UTC, Christdej commented on api/Controllers/WorkflowsControlller.cs
> +            return NotFound();
```suggestion
            return NotFound($"Could not find workflow with inspection id {inspectionId}");
```

2024-11-14 06:08 UTC, Christdej commented on api/Controllers/WorkflowsControlller.cs
> +            return NotFound();
```suggestion
            return NotFound($"Could not find workflow with inspection id {inspectionId}");
```

2024-11-14 10:52 UTC, olaals commented on api/Controllers/WorkflowsControlller.cs
> +public class WorkflowsController(ILogger<InspectionDataController> logger, IInspectionDataService inspectionDataService) : ControllerBase
Removed it for now

2024-11-14 10:52 UTC, olaals commented on api/Controllers/WorkflowsControlller.cs
> +            return NotFound();
Accepted suggestion

2024-11-15 13:24 UTC, Christdej approved these changes
LGTM

2024-11-15 14:03 UTC, merged